[project]
name = "rlm-python"
version = "0.1.0"
description = "FreeRADIUS Kubidm module"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["kubidm"]

[dependency-groups]
dev = ["mypy>=2.3.1", "pytest>=9.1.1", "ruff>=0.16.10", "ty>=0.0.84"]

[tool.uv.sources]
kubidm = { path = "../pykubidm" }
