[package]
name = "rlm_kanidm"
description = "Kubidm FreeRADIUS module core and FFI surface"

version = { workspace = true }
authors = { workspace = true }
rust-version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[lib]
name = "rlm_kanidm"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[features]
extern-freeradius-module = []

[dependencies]
anyhow = { workspace = true }
concread = { workspace = true }
kubidm_client = { workspace = true }
kubidm_proto = { workspace = true }
libc = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
tracing = { workspace = true }

rlm_kanidm_shared = { workspace = true }

[dev-dependencies]
kubidmd_core = { workspace = true }
kubidmd_testkit = { workspace = true }
url = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[build-dependencies]
bindgen = "0.72.0"
cc = "^1.2.63"
